### ISSUE TITLE
device-opcua-go 在fuji版本get和set指令有误

### ISSUE THREAD

**Issue by SHILIANG17671467654** [edgexfoundry/device-opc-ua#4]
拉取源码直接编译运行后，通过subscribe可以正常拿到opcua server的数据，但是调用get和set指令无法获取设备数据。使用postman测试时：执行：http://192.168.194.131:48082/api/v1/device/ce679a4e-fdbc-4bc8-960b-118c787b14fb/command/8f4e73b7-7a63-4177-94f6-282276f9276a，得到的结果：
Get http://localhost:49997/api/v1/device/ce679a4e-fdbc-4bc8-960b-118c787b14fb/CounterNum?: dial tcp [::1]:49997: connect: cannot assign requested address
将get请求改为：http://192.168.194.131:49997/api/v1/device/ce679a4e-fdbc-4bc8-960b-118c787b14fb/CounterNum后，得到：
{
    "device": "SimulationServer",
    "origin": 1587744503531,
    "readings": [
        {
            "origin": 1587744503523,
            "device": "SimulationServer",
            "name": "ns=3;s=Counter",
            "value": "51"
        }
    ]
}此时可以正常拿到数据

**Comment by jiekechoo** [comment]
plaese upgrade to v3, close.
