### ISSUE TITLE
Support Reuse OPCuaClient to enhance performance

### ISSUE THREAD

**Issue by ethan256** [edgexfoundry/device-opc-ua#47]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for `device-opc-ua`

### Description [**REQUIRED**]
 
When performance pressure testing the opcua acquisition, it was found that when acquiring 5000 points per second, the cpu usage was nearly 100%. After pprof, we found that the performance bottleneck occurs in HandleReadCommands and HandleWriteCommands functions. These two functions will build an OPCuaClient instance for each point, and then perform Dial, which leads to an increase in the number of points will consume more CPU.

### Describe the solution you'd like

Reuse OPCuaClient

**Comment by jiekechoo** [comment]
#48 related

**Comment by jiekechoo** [comment]
Closes #48
