### ISSUE TITLE
OPC-UA Integration to EdgeX Foundry

### ISSUE THREAD

**Issue by CesarCastillo-90** [edgexfoundry/device-opc-ua#5]
Hello everyone, I hope you are all right, How can I integrate the OPC-UA microservice to EdgeX Foundry? That is, according to the repository on GitHub, what are the commands or steps to add this service to the Hanoi docker? arm64? I'm using this docker.
[docker-compose-hanoi-arm64.zip](https://github.com/edgexfoundry-holding/device-opcua-go/files/5717075/docker-compose-hanoi-arm64.zip)
 
Thank you for your help, I look forward to your valuable responses.

**Comment by jiekechoo** [comment]
please upgrade to v3, closed.
