### ISSUE TITLE
OOM will occur when large amounts of data are collected

### ISSUE THREAD

**Issue by ethan256** [edgexfoundry/device-opc-ua#53]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
When collecting a large amount of data, even if the [Retention](https://docs.edgexfoundry.org/3.2/microservices/core/data/details/DataRetention/) policy is configured in core-data, the database service that will edgex after a period of time will still experience OOM.

vms:
cpu: 4
memory: 8GB

### Description and Minimal Reproduction [**REQUIRED**]
1. Start a opcua server simulator. You can write an opcua server-side program using python.
2. Build the [docker compose file](https://github.com/edgexfoundry/edgex-compose)
3. Using environment variables to override the core-data configuration
```
RETENTION_ENABLED: true 
RETENTION_INTERVAL: 10s  
RETENTION_MAXCAP: 10
RETENTION_MINCAP: 5  
```
5. start docker compose services.
6. Create deviceprofile and device via [api](https://docs.edgexfoundry.org/3.2/microservices/core/metadata/ApiReference/)
7. Enable logging of core-data service as DEBUG in consul and observation service resource utilization

## 🔥 Exception or Error
1. Increasing number of keys in redis, OOM in VMs.
2. debug logs:   "Prepare to delete 0 readings"

## 🌍  Your Environment
**Deployment Environment:**
ubuntu22.04-wsl2

**EdgeX Version [**REQUIRED**]:**
3.2.0

**Anything else relevant?**
1. after 11h, redis service restart
![image](https://github.com/edgexfoundry/device-opc-ua/assets/46949410/38b16df7-27ab-4b60-b10b-2a4268725ac3)
2. Number of keys in redis over 1000w
![image](https://github.com/edgexfoundry/device-opc-ua/assets/46949410/8c9246d2-99db-41e8-a611-947a92e79f21)
![image](https://github.com/edgexfoundry/device-opc-ua/assets/46949410/f4458f04-3c28-4678-8f7a-be4865eaf135)

**Comment by cloudxxx8** [comment]
Please try to set `WRITABLE_PERSISTDATA: 'false'` in core-data to confirm whether it is the device-opc-ua issue
